--Select the required role
USE ROLE ACCOUNTADMIN;

--Select the required warehouse
USE WAREHOUSE COMPUTE_WH;

--Create the required database
CREATE OR REPLACE DATABASE SALES_DB;

--Select the new database
USE DATABASE SALES_DB;

--Create the BRONZE Schema
CREATE OR REPLACE SCHEMA BRONZE;

--Create the SILVER Schema
CREATE OR REPLACE SCHEMA SILVER;

--Create the GOLD Schema
CREATE OR REPLACE SCHEMA GOLD;

--Use the BRONZE Schema
USE SCHEMA SALES_DB.BRONZE;

-- Setup the Internal Stage
CREATE OR REPLACE STAGE SALES_DB.BRONZE.SALES_STAGE
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER =
1);

--Create the Sales Bronze table
CREATE OR REPLACE TABLE SALES_DB.BRONZE.SALES_BRONZE (
ORDER_ID STRING,
CUSTOMER_ID STRING,
PRODUCT_ID STRING,
ORDER_DATE STRING,
QUANTITY STRING,
PRICE STRING,
REGION STRING,
PAYMENT_METHOD STRING
);

-- Create Stream on the BRONZE table
CREATE OR REPLACE STREAM SALES_DB.BRONZE.SALES_BRONZE_STREAM ON TABLE
SALES_DB.BRONZE.SALES_BRONZE;

--Create the task to load the Bronze table
CREATE OR REPLACE TASK SALES_DB.BRONZE.LOAD_SALES_BRONZE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTES'
AS
COPY INTO SALES_DB.BRONZE.SALES_BRONZE
FROM @SALES_DB.BRONZE.SALES_STAGE
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER =
1);

--Use the SILVER Schema
USE SCHEMA SALES_DB.SILVER;

--Create the Sales Silver table
CREATE OR REPLACE TABLE SALES_DB.SILVER.SALES_SILVER (
ORDER_ID STRING,
CUSTOMER_ID STRING,
PRODUCT_ID STRING,
ORDER_DATE DATE,
QUANTITY INTEGER,
PRICE FLOAT,
REGION STRING,
PAYMENT_METHOD STRING,
TOTAL_AMOUNT INTEGER,
ORDER_PRIORITY STRING,
INSERT_DTS TIMESTAMP
);

-- Create Stream on the SILVER table
CREATE OR REPLACE STREAM SALES_DB.SILVER.SALES_SILVER_STREAM ON TABLE
SALES_DB.SILVER.SALES_SILVER;

--Create the task to load the Silver table
CREATE OR REPLACE TASK SALES_DB.SILVER.LOAD_SALES_SILVER
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTES'
WHEN SYSTEM$STREAM_HAS_DATA('SALES_DB.BRONZE.SALES_BRONZE_STREAM')
AS
INSERT INTO SALES_DB.SILVER.SALES_SILVER
SELECT
ORDER_ID AS ORDER_ID,
CUSTOMER_ID AS CUSTOMER_ID,
PRODUCT_ID AS PRODUCT_ID,
CAST(ORDER_DATE AS DATE) AS ORDER_DATE,
CAST(QUANTITY AS INT) AS QUANTITY,
CAST(PRICE AS FLOAT) AS PRICE,
REGION AS REGION,
PAYMENT_METHOD AS PAYMENT_METHOD,
QUANTITY * PRICE AS TOTAL_AMOUNT,
CASE
WHEN QUANTITY * PRICE > 1000 THEN 'HIGH'
WHEN QUANTITY * PRICE BETWEEN 500 AND 1000 THEN 'MEDIUM'
ELSE 'LOW'
END AS ORDER_PRIORITY,
CURRENT_TIMESTAMP() AS INSERT_DTS
FROM SALES_DB.BRONZE.SALES_BRONZE_STREAM
WHERE QUANTITY > 0
AND PRICE > 0;

--Create the Sales Gold Table
CREATE OR REPLACE TABLE SALES_DB.GOLD.SALES_GOLD (
REGION STRING,
PRODUCT_ID STRING,
MONTH DATE,
TOTAL_QUANTITY INTEGER,
TOTAL_SALES FLOAT,
INSERT_DTS TIMESTAMP,
UPDATE_DTS TIMESTAMP
);

--Create the task to load the Gold table
CREATE OR REPLACE TASK SALES_DB.GOLD.LOAD_SALES_GOLD
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTES'
WHEN SYSTEM$STREAM_HAS_DATA('SALES_DB.SILVER.SALES_SILVER_STREAM')
AS
MERGE INTO SALES_DB.GOLD.SALES_GOLD AS G
USING (
SELECT
S.REGION,
S.PRODUCT_ID,
DATE_TRUNC('MONTH', S.ORDER_DATE) AS MONTH,
SUM(S.QUANTITY) AS TOTAL_QUANTITY,
SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM SALES_DB.SILVER.SALES_SILVER S
JOIN SALES_DB.SILVER.SALES_SILVER_STREAM ST ON S.ORDER_ID = ST.ORDER_ID
WHERE ST.METADATA$ACTION = 'INSERT'
GROUP BY S.REGION, S.PRODUCT_ID, MONTH
) AS AGG
ON G.REGION = AGG.REGION AND G.PRODUCT_ID = AGG.PRODUCT_ID AND G.MONTH =
AGG.MONTH
WHEN MATCHED THEN
UPDATE SET TOTAL_QUANTITY = G.TOTAL_QUANTITY + AGG.TOTAL_QUANTITY,
TOTAL_SALES = G.TOTAL_SALES + AGG.TOTAL_SALES,
UPDATE_DTS = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
INSERT (REGION, PRODUCT_ID, MONTH, TOTAL_QUANTITY,
TOTAL_SALES,INSERT_DTS,UPDATE_DTS)
VALUES (AGG.REGION, AGG.PRODUCT_ID, AGG.MONTH, AGG.TOTAL_QUANTITY,
AGG.TOTAL_SALES,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

--Use the BRONZE Schema
USE SCHEMA SALES_DB.BRONZE;

--List down the task
SHOW TASKS;

--Load and Test the data in the BRONZE tables
ALTER TASK SALES_DB.BRONZE.LOAD_SALES_BRONZE RESUME;

--Select data from the BRONZE table
SELECT * FROM SALES_DB.BRONZE.SALES_BRONZE;

--Select data from the BRONZE Stream
SELECT * FROM SALES_DB.BRONZE.SALES_BRONZE_STREAM;

--Use the SILVER Schema
USE SCHEMA SALES_DB.SILVER;

--Load and Test the data in the SILVER tables
ALTER TASK SALES_DB.SILVER.LOAD_SALES_SILVER RESUME;

--Select data from the SILVER table
SELECT * FROM SALES_DB.SILVER.SALES_SILVER;

--Select data from the SILVER Stream
SELECT * FROM SALES_DB.SILVER.SALES_SILVER_STREAM;

--Use the GOLD Schema
USE SCHEMA SALES_DB.GOLD;

--Load and Test the data in the GOLD tables
ALTER TASK SALES_DB.GOLD.LOAD_SALES_GOLD RESUME;

--Select data from the GOLD table
SELECT * FROM SALES_DB.GOLD.SALES_GOLD;

--Once Tested Suspend your TASKS
ALTER TASK SALES_DB.BRONZE.LOAD_SALES_BRONZE SUSPEND;
ALTER TASK SALES_DB.SILVER.LOAD_SALES_SILVER SUSPEND;
ALTER TASK SALES_DB.GOLD.LOAD_SALES_GOLD SUSPEND;

